"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ReactFlow,ReactFlowProvider,Background,BackgroundVariant,Controls,MiniMap,Handle,Position,addEdge,useNodesState,useEdgesState,MarkerType,applyNodeChanges,type Node,type Edge,type Connection,type NodeProps,type NodeChange,type ReactFlowInstance} from "@xyflow/react";
import "@xyflow/react/dist/style.css";import "./wiring.css";import "./mvp.css";
import {api} from "./api";import {TemplateEditor} from "./TemplateEditor";import type {Endpoint,Project,ProjectInput,Rules,Template,Validation} from "./types";
type Device={instanceId:string;template:Template;[key:string]:unknown};
const parse=(value:string|null):Pick<Endpoint,"connector"|"pin">|null=>{if(!value)return null;const [connector,pin]=value.split(":");return connector&&Number(pin)?{connector,pin:Number(pin)}:null};
function DeviceNode({data,selected}:NodeProps<Node<Device>>){const d=data as Device;const [search,setSearch]=useState("");const [open,setOpen]=useState<Record<string,boolean>>(()=>Object.fromEntries(d.template.connectors.map(c=>[c.id,true])));return <div className={`device ${selected?"selected":""}`}><header><span>{d.template.name.slice(0,2)}</span><div><b>{d.instanceId}</b><small>{d.template.id}</small></div><em>•••</em></header><label className="node-search">⌕<input placeholder="Find pin…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="node-connectors">{d.template.connectors.map(c=>{const pins=c.pins.filter(p=>`${p.number} ${p.name} ${p.type}`.toLowerCase().includes(search.toLowerCase()));return <section key={c.id}><button className="connector-toggle" onClick={()=>setOpen({...open,[c.id]:!open[c.id]})}><b>{open[c.id]?"▾":"▸"} {c.id}</b><small>{pins.length} / {c.pin_count} PINS</small></button>{open[c.id]&&pins.map(p=><div className="pin" key={p.number}><Handle id={`${c.id}:${p.number}`} type="target" position={Position.Left}/><code>{String(p.number).padStart(2,"0")}</code><span><b>{p.name}</b><small>{p.type}</small></span>{p.allow_multiple&&<abbr title="Multiple connections allowed">M</abbr>}<i className={p.direction.toLowerCase()}>{p.direction==="IN"?"←":p.direction==="OUT"?"→":"↔"}</i><Handle id={`${c.id}:${p.number}`} type="source" position={Position.Right}/></div>)}</section>})}</div></div>}
const nodeTypes={device:DeviceNode};
function Workspace(){
 const [templates,setTemplates]=useState<Template[]>([]),[rules,setRules]=useState<Rules|null>(null),[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[validation,setValidation]=useState<Validation|null>(null);const [nodes,setNodes]=useNodesState<Node<Device>>([]),[edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]);const [query,setQuery]=useState(""),[tab,setTab]=useState<"connections"|"checks">("connections"),[msg,setMsg]=useState("Loading project data…"),[busy,setBusy]=useState(true),[dirty,setDirty]=useState(false),[rf,setRf]=useState<ReactFlowInstance<Node<Device>,Edge>|null>(null),[editor,setEditor]=useState<Template|"new"|null>(null);const importRef=useRef<HTMLInputElement>(null);
 const hydrate=useCallback((next:Project,allTemplates:Template[])=>{setProject(next);setNodes(next.instances.flatMap(i=>{const template=allTemplates.find(t=>t.id===i.template_id);return template?[{id:i.id,type:"device",position:i.position,data:{instanceId:i.id,template}}]:[]}));setEdges(next.connections.map(c=>({id:c.id,source:c.from.component,target:c.to.component,sourceHandle:`${c.from.connector}:${c.from.pin}`,targetHandle:`${c.to.connector}:${c.to.pin}`,type:"smoothstep",animated:true,markerEnd:{type:MarkerType.ArrowClosed}})));setValidation(null);setDirty(false)},[setEdges,setNodes]);
 const refresh=useCallback(async(preferred?:string)=>{setBusy(true);try{const [ts,rs,ps]=await Promise.all([api.templates(),api.rules(),api.projects()]);setTemplates(ts);setRules(rs);let selected=ps.find(p=>p.id===(preferred||project?.id))||ps[0];if(!selected)selected=await api.createProject({name:"Untitled Wiring Project",instances:[],connections:[]});const list=ps.some(p=>p.id===selected.id)?ps:[selected,...ps];setProjects(list);hydrate(selected,ts);setMsg("Project loaded from the authoritative API") }catch(e){setMsg(`Backend unavailable: ${e instanceof Error?e.message:"connection failed"}`)}finally{setBusy(false)}},[hydrate,project?.id]);
 // Initial synchronization with the authoritative API.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void refresh()},[]);
 const detail=useCallback((nodeId:string|null,handle:string|null)=>{const node=nodes.find(n=>n.id===nodeId),endpoint=parse(handle);if(!node||!endpoint)return null;const pin=node.data.template.connectors.find(c=>c.id===endpoint.connector)?.pins.find(p=>p.number===endpoint.pin);return pin?{node,pin,connector:endpoint.connector}:null},[nodes]);
 const instantError=useCallback((c:Connection)=>{if(!rules)return "Compatibility rules are still loading";const a=detail(c.source,c.sourceHandle),b=detail(c.target,c.targetHandle);if(!a||!b)return "Pin reference does not exist";if(c.source===c.target)return "Connect two different components";if(!(rules.pin_types[a.pin.type]?.includes(b.pin.type)||rules.pin_types[b.pin.type]?.includes(a.pin.type)))return `${a.pin.type} cannot connect to ${b.pin.type}`;const directionOk=(a.pin.direction==="OUT"||a.pin.direction==="BIDIRECTIONAL")&&(b.pin.direction==="IN"||b.pin.direction==="BIDIRECTIONAL")||rules.direction_exceptions.some(([x,y])=>x===a.pin.direction&&y===b.pin.direction);if(!directionOk)return `${a.pin.direction} to ${b.pin.direction} is not allowed`;if(!b.pin.allow_multiple&&edges.some(e=>e.target===c.target&&e.targetHandle===c.targetHandle))return "Target pin is already occupied";return null},[detail,edges,rules]);
 const connect=useCallback((c:Connection)=>{const error=instantError(c);if(error){setMsg(error);return}setEdges(es=>addEdge({...c,id:`conn_${crypto.randomUUID().slice(0,12)}`,type:"smoothstep",animated:true,markerEnd:{type:MarkerType.ArrowClosed}},es));setDirty(true);setValidation(null);setMsg("Connection added — save to run full validation")},[instantError,setEdges]);
 const onNodesChange=useCallback((changes:NodeChange<Node<Device>>[])=>{setNodes(current=>applyNodeChanges(changes,current));if(changes.some(c=>c.type==="position"||c.type==="remove")){setDirty(true);setValidation(null)}},[setNodes]);
 const model=useCallback(():ProjectInput=>({name:project?.name||"Untitled Wiring Project",instances:nodes.map(n=>({id:n.id,template_id:n.data.template.id,position:n.position})),connections:edges.flatMap(e=>{const from=parse(e.sourceHandle||null),to=parse(e.targetHandle||null);return from&&to?[{id:e.id,from:{component:e.source,...from},to:{component:e.target,...to}}]:[]})}),[edges,nodes,project?.name]);
 const save=async(runValidation=true)=>{if(!project)return;setBusy(true);try{const saved=await api.saveProject(project.id,model());setProject(saved);setProjects(ps=>ps.map(p=>p.id===saved.id?saved:p));setDirty(false);if(runValidation){const result=await api.validate(saved.id);setValidation(result);setTab("checks");setMsg(result.valid?"Validation passed":"Validation found errors") }else setMsg("Project saved") }catch(e){setMsg(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}};
 const add=(template:Template,position={x:80+nodes.length*35,y:90+nodes.length*28})=>{let i=1;while(nodes.some(n=>n.id===`${template.name}${i}`))i++;const id=`${template.name}${i}`;setNodes(ns=>[...ns,{id,type:"device",position,data:{instanceId:id,template}}]);setDirty(true);setValidation(null);setMsg(`${id} added`)};
 const openProject=async(id:string)=>{if(dirty&&!confirm("Discard unsaved changes and open another project?"))return;try{hydrate(await api.getProject(id),templates);setMsg("Project reopened from SQLite")}catch(e){setMsg(e instanceof Error?e.message:"Open failed")}};
 const newProject=async()=>{const name=prompt("Project name","New Wiring Project");if(!name)return;const created=await api.createProject({name,instances:[],connections:[]});setProjects([created,...projects]);hydrate(created,templates)};
 const focusViolation=(connectionId?:string)=>{if(!connectionId)return;setEdges(es=>es.map(e=>({...e,selected:e.id===connectionId})));const edge=edges.find(e=>e.id===connectionId);if(edge&&rf){const a=nodes.find(n=>n.id===edge.source),b=nodes.find(n=>n.id===edge.target);if(a&&b)rf.fitBounds({x:Math.min(a.position.x,b.position.x),y:Math.min(a.position.y,b.position.y),width:Math.abs(a.position.x-b.position.x)+240,height:Math.abs(a.position.y-b.position.y)+180},{padding:.3})}}
 if(busy&&!project)return <main className="boot"><b>Visual Wiring</b><span>Loading templates, projects, and rules…</span></main>;
 return <main><nav><strong className="logo">W</strong><div className="brand"><b>Visual Wiring</b><small>Definition Tool</small></div><div className="project project-picker"><small>PROJECT</small><select value={project?.id||""} onChange={e=>openProject(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></div><button className="nav-secondary" onClick={newProject}>＋ Project</button><span className={`saved ${dirty?"unsaved":""}`}>● {dirty?"Unsaved changes":"Saved"}</span><button disabled={busy||!project} onClick={()=>save(true)}>✓ Save & Validate</button><div className="export-menu"><button disabled={!project||dirty||validation?.valid!==true} onClick={()=>project&&api.download(project.id,"csv")}>CSV</button><button disabled={!project||dirty||validation?.valid!==true} onClick={()=>project&&api.download(project.id,"excel")}>Excel</button></div></nav><div className="layout">
 <aside className="library"><div className="title"><span><small>COMPONENT</small><h2>Library</h2></span><button onClick={()=>setEditor("new")} title="Create template">+</button></div><label className="search">⌕<input placeholder="Search components…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="library-actions"><button onClick={()=>importRef.current?.click()}>Import JSON</button><input ref={importRef} hidden type="file" accept="application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{await api.importTemplate(JSON.parse(await file.text()));await refresh();setMsg("Template imported")}catch(error){setMsg(error instanceof Error?error.message:"Import failed")}e.target.value=""}}/></div><div className="cards">{templates.filter(t=>(t.name+t.id+t.description).toLowerCase().includes(query.toLowerCase())).map(t=><div className="template-row" key={t.id}><button draggable onDragStart={e=>e.dataTransfer.setData("template",t.id)} onDoubleClick={()=>add(t)}><strong>{t.name.slice(0,2)}</strong><span><b>{t.name}</b><small>{t.id} · {t.connectors.reduce((n,c)=>n+c.pins.length,0)} pins</small></span><em>⠿</em></button><div><button title="Edit" onClick={()=>setEditor(t)}>✎</button><button title="Export JSON" onClick={()=>{const blob=new Blob([JSON.stringify(t,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${t.id}.json`;a.click();URL.revokeObjectURL(url)}}>⇩</button><button title="Delete" onClick={async()=>{if(!confirm(`Delete ${t.id}?`))return;try{await api.deleteTemplate(t.id);await refresh();setMsg("Template deleted")}catch(e){setMsg(e instanceof Error?e.message:"Delete failed")}}}>×</button></div></div>)}</div><div className="tip"><b>Library is server-backed</b><small>Create, edit, import, export, or drag a template onto the canvas.</small></div></aside>
 <section className="flow" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const t=templates.find(x=>x.id===e.dataTransfer.getData("template"));if(t&&rf)add(t,rf.screenToFlowPosition({x:e.clientX,y:e.clientY}))}}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={changes=>{onEdgesChange(changes);if(changes.some(c=>c.type==="remove")){setDirty(true);setValidation(null)}}} onNodesDelete={deleted=>setEdges(es=>es.filter(e=>!deleted.some(n=>n.id===e.source||n.id===e.target)))} onConnect={connect} isValidConnection={c=>!instantError(c)} onInit={setRf} fitView deleteKeyCode={["Delete","Backspace"]}><Background variant={BackgroundVariant.Dots} gap={18} size={1.2}/><Controls/><MiniMap pannable zoomable/>{nodes.length===0&&<div className="empty"><span>＋</span><b>Build your wiring map</b><small>Drag a server-backed component template here.</small></div>}</ReactFlow><div className={`toast ${/cannot|not allowed|occupied|unavailable|failed/i.test(msg)?"bad":""}`}>● {msg}</div></section>
 <aside className="inspect"><div className="tabs"><button className={tab==="connections"?"active":""} onClick={()=>setTab("connections")}>Connections <i>{edges.length}</i></button><button className={tab==="checks"?"active":""} onClick={()=>setTab("checks")}>Validation <i>{validation?.summary.errors??"–"}</i></button></div>{tab==="connections"?<><div className="panel-title"><small>SAVED PROJECT MODEL</small><h2>Pin-to-Pin</h2></div><div className="connection-list">{edges.length===0?<div className="none"><b>⌁</b><strong>No connections yet</strong><small>Draw a wire between compatible handles.</small></div>:edges.map((e,i)=>{const a=detail(e.source,e.sourceHandle||null),b=detail(e.target,e.targetHandle||null);return a&&b?<div className="connection" key={e.id}><i>{i+1}</i><span><b>{a.node.id}.{a.connector} <em>Pin {a.pin.number}</em></b><small>↓</small><b>{b.node.id}.{b.connector} <em>Pin {b.pin.number}</em></b><code>{a.pin.name} · {a.pin.type}</code></span></div>:null})}</div><div className="json"><header><b>Connection references</b><small>No duplicated pin metadata</small></header><pre>{JSON.stringify(model().connections,null,2)}</pre></div></>:<div className="check-list"><div className="panel-title"><small>AUTHORITATIVE SERVER RESULT</small><h2>{validation?validation.valid?"Validation passed":"Action required":"Not validated"}</h2></div>{!validation?<div className="none"><b>✓</b><strong>Save & Validate</strong><small>Results appear only after the backend validator runs.</small></div>:validation.violations.length===0?<div className="none valid-empty"><b>✓</b><strong>No violations</strong><small>{validation.graph.pin_nodes} pins and {validation.graph.pin_edges} connections checked.</small></div>:validation.violations.map((v,i)=><button className="violation" key={`${v.rule_id}-${i}`} onClick={()=>focusViolation(v.connection_id)}><i className={v.severity}>{v.severity==="error"?"!":"△"}</i><span><b>{v.rule_id}</b><small>{v.message}</small></span></button>)}</div>}<footer className={validation?.valid?"pass":validation?"fail":""}>● <span><b>{validation?`${validation.summary.errors} errors · ${validation.summary.warnings} warnings`:"Awaiting validation"}</b><small>{validation?"Result returned by FastAPI Rule Engine":"Save the project to validate"}</small></span></footer></aside>
 </div>{editor&&<TemplateEditor initial={editor==="new"?undefined:editor} onClose={()=>setEditor(null)} onSave={async value=>{if(editor==="new")await api.createTemplate(value);else await api.updateTemplate(editor.id,value);setEditor(null);await refresh();setMsg("Component template saved")}}/>}</main>}
export default function Home(){return <ReactFlowProvider><Workspace/></ReactFlowProvider>}
