"use client";
import {useCallback,useMemo,useState} from "react";
import {ReactFlow,ReactFlowProvider,Background,BackgroundVariant,Controls,MiniMap,Handle,Position,addEdge,useNodesState,useEdgesState,MarkerType,type Node,type Edge,type Connection,type NodeProps} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import "./wiring.css";

type Pin={pin:number;name:string;type:string;direction:"IN"|"OUT"|"BIDIRECTIONAL"};
type Conn={id:string;pin_count:number;pins:Pin[]};
type Template={id:string;name:string;family:string;connectors:Conn[]};
type Device={instanceId:string;template:Template;[key:string]:unknown};
const library:Template[]=[
 {id:"PACK_CONN",name:"PACK",family:"Connector",connectors:[{id:"J1",pin_count:4,pins:[{pin:1,name:"CAN_H",type:"CAN_H",direction:"BIDIRECTIONAL"},{pin:2,name:"CAN_L",type:"CAN_L",direction:"BIDIRECTIONAL"},{pin:3,name:"KL30_12V",type:"POWER_12V_OUT",direction:"OUT"},{pin:4,name:"PACK_NTC",type:"NTC_SENSOR",direction:"OUT"}]}]},
 {id:"BASU_A",name:"BASU",family:"Controller",connectors:[{id:"P1",pin_count:8,pins:[{pin:1,name:"CAN_H",type:"CAN_H",direction:"BIDIRECTIONAL"},{pin:2,name:"CAN_L",type:"CAN_L",direction:"BIDIRECTIONAL"},{pin:3,name:"NTC_1",type:"NTC_INPUT",direction:"IN"},{pin:4,name:"VBAT_12V",type:"POWER_12V_IN",direction:"IN"}]}]},
 {id:"BIC_A",name:"BIC",family:"Daisy chain",connectors:[{id:"P1",pin_count:2,pins:[{pin:1,name:"ISO_IN+",type:"DAISY_IN",direction:"IN"},{pin:2,name:"ISO_IN-",type:"DAISY_IN",direction:"IN"}]},{id:"P2",pin_count:2,pins:[{pin:1,name:"ISO_OUT+",type:"DAISY_OUT",direction:"OUT"},{pin:2,name:"ISO_OUT-",type:"DAISY_OUT",direction:"OUT"}]}]},
 {id:"NTC_10K",name:"NTC",family:"Sensor",connectors:[{id:"S1",pin_count:2,pins:[{pin:1,name:"NTC_OUT",type:"NTC_SENSOR",direction:"OUT"},{pin:2,name:"GND",type:"GND",direction:"OUT"}]}]}
];
const rules:Record<string,string[]>={CAN_H:["CAN_H"],CAN_L:["CAN_L"],NTC_SENSOR:["NTC_INPUT","ADC_NTC"],POWER_12V_OUT:["POWER_12V_IN"],DAISY_OUT:["DAISY_IN"],GND:["GND"]};
const parse=(x:string|null)=>{if(!x)return null;const [connector,p]=x.split(":");return {connector,pin:+p}};
function DeviceNode({data,selected}:NodeProps<Node<Device>>){const d=data as Device;return <div className={`device ${selected?"selected":""}`}><header><span>{d.template.name.slice(0,2)}</span><div><b>{d.instanceId}</b><small>{d.template.id}</small></div><em>•••</em></header>{d.template.connectors.map(c=><section key={c.id}><h4><b>{c.id}</b><small>{c.pins.length} / {c.pin_count} PINS</small></h4>{c.pins.map(p=><div className="pin" key={p.pin}><Handle id={`${c.id}:${p.pin}`} type="target" position={Position.Left}/><code>{String(p.pin).padStart(2,"0")}</code><span><b>{p.name}</b><small>{p.type}</small></span><i className={p.direction.toLowerCase()}>{p.direction==="IN"?"←":p.direction==="OUT"?"→":"↔"}</i><Handle id={`${c.id}:${p.pin}`} type="source" position={Position.Right}/></div>)}</section>)}</div>}
const nodeTypes={device:DeviceNode};
function App(){
 const [nodes,setNodes,onNodesChange]=useNodesState<Node<Device>>([]);const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]);const [query,setQuery]=useState("");const [tab,setTab]=useState("connections");const [msg,setMsg]=useState("Ready — drag a component into the canvas");const [rf,setRf]=useState<any>();
 const detail=useCallback((nodeId:string|null,h:string|null)=>{const n=nodes.find(x=>x.id===nodeId),q=parse(h);if(!n||!q)return null;const p=n.data.template.connectors.find(c=>c.id===q.connector)?.pins.find(x=>x.pin===q.pin);return p?{n,p,c:q.connector}:null},[nodes]);
 const invalid=useCallback((c:Connection)=>{const a=detail(c.source,c.sourceHandle),b=detail(c.target,c.targetHandle);if(!a||!b)return "Pin reference does not exist";if(c.source===c.target)return "Connect two different components";if(edges.some(e=>e.source===c.source&&e.sourceHandle===c.sourceHandle&&e.target===c.target&&e.targetHandle===c.targetHandle))return "Connection already exists";if(!(rules[a.p.type]?.includes(b.p.type)||rules[b.p.type]?.includes(a.p.type)||a.p.type===b.p.type))return `${a.p.type} cannot connect to ${b.p.type}`;if(a.p.direction===b.p.direction&&a.p.direction!=="BIDIRECTIONAL")return `${a.p.direction} → ${b.p.direction} is not allowed`;if(edges.some(e=>e.target===c.target&&e.targetHandle===c.targetHandle))return "Target pin is already occupied";return null},[detail,edges]);
 const connect=useCallback((c:Connection)=>{const error=invalid(c);if(error){setMsg(error);return}setEdges(es=>addEdge({...c,id:`wire-${Date.now()}`,type:"smoothstep",animated:true,markerEnd:{type:MarkerType.ArrowClosed}},es));setMsg("Connection created and validated")},[invalid,setEdges]);
 const add=(t:Template,pos={x:90+nodes.length*35,y:100+nodes.length*28})=>{let i=1;while(nodes.some(n=>n.id===`${t.name}${i}`))i++;const id=`${t.name}${i}`;setNodes(ns=>[...ns,{id,type:"device",position:pos,data:{instanceId:id,template:t}}]);setMsg(`${id} added to project`)};
 const model=useMemo(()=>edges.map(e=>({from:{component:e.source,...parse(e.sourceHandle||null)!},to:{component:e.target,...parse(e.targetHandle||null)!}})),[edges]);
 const csv=()=>{const h=["From Device","From Connector","From Pin","From Signal","From Type","To Device","To Connector","To Pin","To Signal","To Type"],rows=edges.map(e=>{const a=detail(e.source,e.sourceHandle||null)!,b=detail(e.target,e.targetHandle||null)!;return[a.n.id,a.c,a.p.pin,a.p.name,a.p.type,b.n.id,b.c,b.p.pin,b.p.name,b.p.type]});const u=URL.createObjectURL(new Blob([[h,...rows].map(r=>r.join(",")).join("\n")],{type:"text/csv"}));const a=document.createElement("a");a.href=u;a.download="wiring-definition.csv";a.click();URL.revokeObjectURL(u);setMsg(`Exported ${rows.length} connections`)};
 const checks=[{n:"Pin references",d:`${edges.length*2} endpoints resolved`,ok:true},{n:"Connection rules",d:`${edges.length} valid wires`,ok:true},{n:"Duplicate inputs",d:"No duplicates",ok:true},{n:"Cycle detection",d:"No cycles",ok:true},{n:"Disconnected devices",d:`${nodes.filter(n=>!edges.some(e=>e.source===n.id||e.target===n.id)).length} isolated`,ok:nodes.length===0||nodes.every(n=>edges.some(e=>e.source===n.id||e.target===n.id))}];
 return <main><nav><strong className="logo">W</strong><div className="brand"><b>Visual Wiring</b><small>Definition Tool</small></div><div className="project"><small>PROJECT</small><b>Battery Control Unit <i>v1.4</i></b></div><span className="saved">● All changes saved</span><button onClick={csv}>⇩ Export CSV</button></nav><div className="layout">
 <aside className="library"><div className="title"><span><small>COMPONENT</small><h2>Library</h2></span><button>+</button></div><label className="search">⌕<input placeholder="Search components…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="cards">{library.filter(t=>(t.name+t.id+t.family).toLowerCase().includes(query.toLowerCase())).map(t=><button key={t.id} draggable onDragStart={e=>e.dataTransfer.setData("template",t.id)} onDoubleClick={()=>add(t)}><strong>{t.name.slice(0,2)}</strong><span><b>{t.name}</b><small>{t.id} · {t.connectors.reduce((a,c)=>a+c.pins.length,0)} pins</small></span><em>⠿</em></button>)}</div><div className="tip"><b>Drag to add</b><small>Drop onto the canvas. Double-click works too.</small></div></aside>
 <section className="flow" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const t=library.find(x=>x.id===e.dataTransfer.getData("template"));if(t&&rf)add(t,rf.screenToFlowPosition({x:e.clientX,y:e.clientY}))}}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} isValidConnection={c=>!invalid(c)} onInit={setRf} fitView deleteKeyCode={["Delete","Backspace"]}><Background variant={BackgroundVariant.Dots} gap={18} size={1.2}/><Controls/><MiniMap pannable zoomable/>{nodes.length===0&&<div className="empty"><span>＋</span><b>Build your wiring map</b><small>Drag components here, then connect individual pins.</small></div>}</ReactFlow><div className={`toast ${msg.includes("cannot")||msg.includes("not allowed")||msg.includes("occupied")?"bad":""}`}>● {msg}</div></section>
 <aside className="inspect"><div className="tabs"><button className={tab==="connections"?"active":""} onClick={()=>setTab("connections")}>Connections <i>{edges.length}</i></button><button className={tab==="checks"?"active":""} onClick={()=>setTab("checks")}>Checks <i>{checks.filter(x=>!x.ok).length}</i></button></div>{tab==="connections"?<><div className="panel-title"><small>LIVE MODEL</small><h2>Pin-to-Pin</h2></div><div className="connection-list">{edges.length===0?<div className="none"><b>⌁</b><strong>No connections yet</strong><small>Draw a wire between two compatible pin handles.</small></div>:edges.map((e,i)=>{const a=detail(e.source,e.sourceHandle||null)!,b=detail(e.target,e.targetHandle||null)!;return <div className="connection" key={e.id}><i>{i+1}</i><span><b>{a.n.id}.{a.c} <em>Pin {a.p.pin}</em></b><small>↓</small><b>{b.n.id}.{b.c} <em>Pin {b.p.pin}</em></b><code>{a.p.name} · {a.p.type}</code></span><strong>✓</strong></div>})}</div><div className="json"><header><b>Connection JSON</b><small>Source of truth</small></header><pre>{JSON.stringify(model,null,2)}</pre></div></>:<div className="check-list"><div className="panel-title"><small>RULE ENGINE</small><h2>Project health</h2></div>{checks.map(x=><div className="check" key={x.n}><i className={x.ok?"ok":"warn"}>{x.ok?"✓":"!"}</i><span><b>{x.n}</b><small>{x.d}</small></span></div>)}</div>}<footer>● <span><b>{checks.filter(x=>x.ok).length}/{checks.length} checks passed</b><small>Ready for server review</small></span></footer></aside>
 </div></main>}
export default function Home(){return <ReactFlowProvider><App/></ReactFlowProvider>}
